### ISSUE TITLE
Is there need more more than one binding?

### ISSUE THREAD

**Issue by drnic** [starkandwayne/eden#2]
Can we optimize around one binding?

**Comment by jhunt** [comment]
At least for the Vault service broker I wrote, each bind operation made different credentials, for auditing purposes.  So if Eden is going to be useful in cases like that, it probably needs to support multiple binds.

**Comment by drnic** [comment]
@jhunt Indeed lots of good brokers generate unique creds per service instance. In part I'm musing about the purpose/role/use cases of eden.
