### ISSUE TITLE
Can we have a 0.7.3 please?

### ISSUE THREAD

**Issue by mkuratczyk** [starkandwayne/eden#21]
Hey,

0.7.2 crashes for us but thanks to https://github.com/starkandwayne/eden/commit/73310be3d323031d26b4d85cc4506195e6a4d25d everything works nicely when using master. Could you please cut 0.7.3 so that the version installed by `brew` doesn't crash? Thanks,

**Comment by drnic** [comment]
Done; thanks for reminder.
